// Generated by 'unplugin-auto-import'
export {}
declare global {
  const ElContainer: typeof import('element-plus/es')['ElContainer']
  const ElDrawer: typeof import('element-plus/es')['ElDrawer']
}
